[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"

[directory]
fish_style_pwd_dir_length = 1

[memory_usage]
threshold = -1
disabled = false

[time]
disabled = false
use_12hr = true

[git_branch]
symbol = "ğŸ’  "

