[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"

[memory_usage]
threshold = -1
disabled = false

[time]
disabled = false
use_12hr = true

[git_branch]
symbol = "ğŸ’  "
 
[env_var.AWS_PROFILE]
default = 'prod'
style = 'bold bright-red'
